services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3z3@QdR@3AKDUMO
      POSTGRES_DB: TFIF
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/TFIF?serverTimezone=America/Lima
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3z3@QdR@3AKDUMO
      # JWT
      JWT_SECRET_KEY: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIZF9zUzoKokFoAUXj70pnEKCcdh98wVP5xBcKhsVUP8pAZFkustM87khx/2G8GY20OMGBdm52v5dtDDXilyuDMCAwEAAQ==
      JWT_EXP_TIME: 604800000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  postgres:
